---
name: 🚀 Push on Merge

on:
  push:
    branches:
      - main
    paths:
      - 'docker/dockerfile'
      - 'build/makefile'
  workflow_dispatch:

jobs:
  push-changes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, linux/arm64/v8]
    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 46800
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Make publish
        working-directory: ./Build
        run: |
          make ARCH=${{ matrix.architecture }} DOCKER_USERNAME=${{ github.repository_owner }}  DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }}  -f makefile publish
