---
name: 🧪 Pull Request Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [linux/amd64, linux/arm64/v8]

    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: cache docker cache
      #  uses: actions/cache@v1
      #  with:
      #    path: ${{ github.workspace }}/cache
      #    key: ${{ runner.os }}-docker-${{ hashfiles('cache/**') }}
      #    restore-keys: |
      #      ${{ runner.os }}-docker-

      #- name: Build
      #  uses: docker/build-push-action@v5
      #  env:
      #    BUILDX_NO_DEFAULT_ATTESTATIONS: 1
      #  with:
      #    context: ./Build/LocalAI
      #    platforms: ${{ matrix.architecture }}
      #    cache-from: type=local,src=$GITHUB_WORKSPACE/cache
      #    cache-to: type=local,dest=$GITHUB_WORKSPACE/cache
      #    provenance: false
      #    tags: |
      #      ghcr.io/ducretje/localai-image:test

      - name: Run Make Test
        working-directory: ./Build
        run: |
          make ARCH=${{ matrix.architecture }} DOCKER_USERNAME=${{ github.repository_owner }}  DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }} -f makefile test

      # - name: Run Make Test
      #   working-directory: ./Build
      #   run: |
      #     make ARCH=${{ matrix.architecture }} DOCKER_USERNAME=${{ github.repository_owner }}  DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }} -f makefile test2

      - name: 🧹 Delete test packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'localai-image'
          package-type: 'container'
          ignore-versions: '.*test.*'
